config/routes.rb
Rails.application.routes.draw do
  resources :hashtags_to_tweets
  resources :hashtags
  devise_for :users
  resources :tweets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  has_many :hashtags_to_tweets
  has_many :tweets, through: :hashtags_to_tweets

  validates :hashtag, uniqueness: true
  validates :hashtag, length: { in: 1..20 }
  validates :hashtag, format: { with: %r{\A(\w|[0-9])+\z}, message: "only allows alphanumeric hashtag" }
end

app/models/hashtags_to_tweet.rb
class HashtagsToTweet < ApplicationRecord
  belongs_to :hashtag
  belongs_to :tweet

  validates :hashtag, presence: true
  validates :tweet, presence: true

  # Find the tweet to get its hashtags
  def find_hashtags_of_tweet(tweet_id)
    htts = HashtagsToTweet.where(tweet_id: tweet_id)
  end
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :hashtags_to_tweets
  has_many :hashtags, through: :hashtags_to_tweets

  validates :body, length: { in: 1..280 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
  before_action :set_hashtag, only: %i[ show edit update destroy ]

  # GET /hashtags or /hashtags.json
  def index
    @hashtags = Hashtag.all
  end

  # GET /hashtags/1 or /hashtags/1.json
  def show
  end

  # GET /hashtags/new
  def new
    @hashtag = Hashtag.new
  end

  # GET /hashtags/1/edit
  def edit
  end

  # POST /hashtags or /hashtags.json
  def create
    @hashtag = Hashtag.new(hashtag_params)

    respond_to do |format|
      if @hashtag.save
        format.html { redirect_to hashtag_url(@hashtag), notice: "Hashtag was successfully created." }
        format.json { render :show, status: :created, location: @hashtag }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hashtag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hashtags/1 or /hashtags/1.json
  def update
    respond_to do |format|
      if @hashtag.update(hashtag_params)
        format.html { redirect_to hashtag_url(@hashtag), notice: "Hashtag was successfully updated." }
        format.json { render :show, status: :ok, location: @hashtag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hashtag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hashtags/1 or /hashtags/1.json
  def destroy
    @hashtag.destroy

    respond_to do |format|
      format.html { redirect_to hashtags_url, notice: "Hashtag was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hashtag
      @hashtag = Hashtag.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hashtag_params
      params.require(:hashtag).permit(:name)
    end
end

app/controllers/hashtags_to_tweets_controller.rb
class HashtagsToTweetsController < ApplicationController
  before_action :set_hashtags_to_tweet, only: %i[ show edit update destroy ]

  # GET /hashtags_to_tweets or /hashtags_to_tweets.json
  def index
    @hashtags_to_tweets = HashtagsToTweet.all
  end

  # GET /hashtags_to_tweets/1 or /hashtags_to_tweets/1.json
  def show
  end

  # GET /hashtags_to_tweets/new
  def new
    @hashtags_to_tweet = HashtagsToTweet.new
  end

  # GET /hashtags_to_tweets/1/edit
  def edit
  end

  # POST /hashtags_to_tweets or /hashtags_to_tweets.json
  def create
    @hashtags_to_tweet = HashtagsToTweet.new(hashtags_to_tweet_params)

    respond_to do |format|
      if @hashtags_to_tweet.save
        format.html { redirect_to hashtags_to_tweet_url(@hashtags_to_tweet), notice: "Hashtags to tweet was successfully created." }
        format.json { render :show, status: :created, location: @hashtags_to_tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hashtags_to_tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hashtags_to_tweets/1 or /hashtags_to_tweets/1.json
  def update
    respond_to do |format|
      if @hashtags_to_tweet.update(hashtags_to_tweet_params)
        format.html { redirect_to hashtags_to_tweet_url(@hashtags_to_tweet), notice: "Hashtags to tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @hashtags_to_tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hashtags_to_tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hashtags_to_tweets/1 or /hashtags_to_tweets/1.json
  def destroy
    @hashtags_to_tweet.destroy

    respond_to do |format|
      format.html { redirect_to hashtags_to_tweets_url, notice: "Hashtags to tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hashtags_to_tweet
      @hashtags_to_tweet = HashtagsToTweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hashtags_to_tweet_params
      params.fetch(:hashtags_to_tweet, {})
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]

  # GET /tweets or /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:body, :user, :created_at, :likes, :new_hashtags)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hashtags_helper.rb
module HashtagsHelper
end

app/helpers/hashtags_to_tweets_helper.rb
module HashtagsToTweetsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/hashtags/_form.html.erb
<%= form_with(model: hashtag) do |form| %>
  <% if hashtag.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(hashtag.errors.count, "error") %> prohibited this hashtag from being saved:</h2>

      <ul>
        <% hashtag.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/hashtags/_hashtag.html.erb
<div id="<%= dom_id hashtag %>">
  <p>
    <strong>Hashtag:</strong>
    <%= hashtag.hashtag %>
  </p>

</div>

app/views/hashtags/edit.html.erb
<h1>Editing hashtag</h1>

<%= render "form", hashtag: @hashtag %>

<br>

<div>
  <%= link_to "Show this hashtag", @hashtag %> |
  <%= link_to "Back to hashtags", hashtags_path %>
</div>

app/views/hashtags/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Hashtags</h1>

<div id="hashtags">
  <% @hashtags.each do |hashtag| %>
    <%= render hashtag %>
    <p>
      <%= link_to "Show this hashtag", hashtag %>
    </p>
  <% end %>
</div>

<%= link_to "New hashtag", new_hashtag_path %>

app/views/hashtags/new.html.erb
<h1>New hashtag</h1>

<%= render "form", hashtag: @hashtag %>

<br>

<div>
  <%= link_to "Back to hashtags", hashtags_path %>
</div>

app/views/hashtags/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @hashtag %>

<div>
  <%= link_to "Edit this hashtag", edit_hashtag_path(@hashtag) %> |
  <%= link_to "Back to hashtags", hashtags_path %>

  <%= button_to "Destroy this hashtag", @hashtag, method: :delete %>
</div>

app/views/hashtags_to_tweets/_form.html.erb
<%= form_with(model: hashtags_to_tweet) do |form| %>
  <% if hashtags_to_tweet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(hashtags_to_tweet.errors.count, "error") %> prohibited this hashtags_to_tweet from being saved:</h2>

      <ul>
        <% hashtags_to_tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <ul>
    <% htts = hashtags_to_tweet.find_hashtags_of_tweet(hashtags_to_tweet.tweet_id) %>
    <% hashtag_list = htts.map { |h| h.hashtag.hashtag } %>
    <% hashtag_list.each do |h| %>
      <li><%= h %></li>
    <% end %>
  </ul>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/hashtags_to_tweets/_hashtags_to_tweet.html.erb
<div id="<%= dom_id hashtags_to_tweet %>">
  <p>
    <strong>Hashtags to tweets:</strong>
    <%= "##{hashtags_to_tweet.hashtag.hashtag}" %> / <%= [hashtags_to_tweet.tweet.body, "@#{hashtags_to_tweet.tweet.user.nickname}"].join(' - ') %>
  </p>
</div>

app/views/hashtags_to_tweets/edit.html.erb
<h1>Editing hashtags to tweet</h1>

<%= render "form", hashtags_to_tweet: @hashtags_to_tweet %>

<br>

<div>
  <%= link_to "Show this hashtag to tweet", @hashtags_to_tweet %> |
  <%= link_to "Back to hashtags to tweets", hashtags_to_tweets_path %>
</div>

app/views/hashtags_to_tweets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Hashtags to tweets</h1>

<div id="hashtags_to_tweets">
  <% @hashtags_to_tweets.each do |hashtags_to_tweet| %>
    <%= render hashtags_to_tweet %>
    <p>
      <%= link_to "Show this hashtag to tweet", hashtags_to_tweet %>
      <%= button_to "Delete this Relation", hashtags_to_tweet, method: :delete, form: { data: { turbo_confirm: "Are you sure?" } } %>
    </p>
  <% end %>
</div>

<%= link_to "New hashtag to tweet", new_hashtags_to_tweet_path %>

app/views/hashtags_to_tweets/new.html.erb
<h1>New hashtag to tweet</h1>

<%= render "form", hashtags_to_tweet: @hashtags_to_tweet %>

<br>

<div>
  <%= link_to "Back to hashtags to tweets", hashtags_to_tweets_path %>
</div>

app/views/hashtags_to_tweets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @hashtags_to_tweet %>

<div>
  <%= link_to "Edit this hashtag to tweet", edit_hashtags_to_tweet_path(@hashtags_to_tweet) %> |
  <%= link_to "Back to hashtag to tweets", hashtags_to_tweets_path %>

  <%= button_to "Destroy this hashtag to tweet", @hashtags_to_tweet, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <% if tweet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.label :user, style: "display: block" %>
    <%= form.number_field :user %>
  </div>

  <div>
    <%= form.label :created_at, style: "display: block" %>
    <%= form.datetime_field :created_at %>
  </div>

  <div>
    <%= form.label :likes, style: "display: block" %>
    <%= form.number_field :likes %>
  </div>

  <div>
    <%= form.label :hashtags, style: "display: block" %>
    <%= form.text_area :new_hashtags, cols: "20", rows: "15" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<div id="<%= dom_id tweet %>">
  <p>
    <strong>Body:</strong>
    <%= tweet.body %>
  </p>

  <p>
    <strong>User:</strong>
    <%= "@#{tweet.user.nickname}" %>
  </p>

  <p>
    <strong>Created at:</strong>
    <%= tweet.created_at %>
  </p>

  <p>
    <strong>Likes:</strong>
    <%# playing with vue may be deleted %>
    <% if tweet.likes.to_s.size > 3 && tweet.likes.to_s.size <= 6 %>
      <% unit = 'k' %>
    <% elsif tweet.likes.to_s.size > 6 && tweet.likes.to_s.size <= 9 %>
      <% unit = 'M' %>
    <% else %>
      <% unit = '' %>
    <% end %>

    <%= tweet.likes %> <%= unit %>
  </p>

</div>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Show this tweet", @tweet %> |
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tweets</h1>

<div id="tweets">
  <% @tweets.each do |tweet| %>
    <%= render tweet %>
    <p>
      <%= link_to "Show this tweet", tweet %>
    </p>
  <% end %>
</div>

<%= link_to "New tweet", new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tweet %>

<div>
  <%= link_to "Edit this tweet", edit_tweet_path(@tweet) %> |
  <%= link_to "Back to tweets", tweets_path %>

  <%= button_to "Destroy this tweet", @tweet, method: :delete %>
</div>